// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://solaris.sherstd.ru' | (string & {});
};

/**
 * Body_import_tasks_api_tasks_upload_import_csv_post
 */
export type BodyImportTasksApiTasksUploadImportCsvPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_log_in_user_api_user_login_post
 */
export type BodyLogInUserApiUserLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_post_tasks_api_tasks_upload_import_json_post
 */
export type BodyPostTasksApiTasksUploadImportJsonPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CheckAnswer
 */
export type CheckAnswer = {
    /**
     * Answer
     */
    answer: string;
    /**
     * Elapsed Ms
     */
    elapsed_ms?: number | null;
};

/**
 * Difficulty
 */
export type Difficulty = 'лёгкий' | 'средний' | 'сложный';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LeaderboardEntry
 */
export type LeaderboardEntry = {
    /**
     * Rank
     */
    rank: number;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Rating
     */
    rating: number;
};

/**
 * LeaderboardResponse
 */
export type LeaderboardResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Entries
     */
    entries: Array<LeaderboardEntry>;
};

/**
 * MatchHistoryItem
 */
export type MatchHistoryItem = {
    /**
     * Match Id
     */
    match_id: string;
    opponent: UserPublic;
    /**
     * My Rating Before
     */
    my_rating_before: number;
    /**
     * My Rating Delta
     */
    my_rating_delta: number;
    /**
     * Result
     */
    result?: string | null;
    /**
     * State
     */
    state: string;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
};

/**
 * MatchHistoryResponse
 */
export type MatchHistoryResponse = {
    /**
     * Items
     */
    items: Array<MatchHistoryItem>;
    /**
     * Limit
     */
    limit: number;
};

/**
 * ProbabilityResponse
 */
export type ProbabilityResponse = {
    /**
     * My Rating
     */
    my_rating: number;
    /**
     * Opponent Rating
     */
    opponent_rating: number;
    /**
     * Expected Score
     */
    expected_score: number;
};

/**
 * ProjectionDeltas
 */
export type ProjectionDeltas = {
    /**
     * Win
     */
    win: number;
    /**
     * Draw
     */
    draw: number;
    /**
     * Loss
     */
    loss: number;
};

/**
 * ProjectionResponse
 */
export type ProjectionResponse = {
    /**
     * My Rating
     */
    my_rating: number;
    /**
     * Opponent Rating
     */
    opponent_rating: number;
    /**
     * K Factor
     */
    k_factor?: number;
    deltas: ProjectionDeltas;
};

/**
 * PvpSummary
 */
export type PvpSummary = {
    /**
     * Matches
     */
    matches: number;
    /**
     * Wins
     */
    wins: number;
    /**
     * Losses
     */
    losses: number;
    /**
     * Draws
     */
    draws: number;
    /**
     * Win Rate Pct
     */
    win_rate_pct: number;
};

/**
 * RatingSummary
 */
export type RatingSummary = {
    user: UserPublic;
    /**
     * Rank
     */
    rank: number;
    /**
     * Percentile Pct
     */
    percentile_pct: number;
    /**
     * Total Players
     */
    total_players: number;
    pvp: PvpSummary;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * StatsPvp
 */
export type StatsPvp = {
    /**
     * Matches
     */
    matches: number;
    /**
     * Wins
     */
    wins: number;
    /**
     * Losses
     */
    losses: number;
    /**
     * Draws
     */
    draws: number;
    /**
     * Win Rate Pct
     */
    win_rate_pct: number;
};

/**
 * StatsResponse
 */
export type StatsResponse = {
    user: UserPublic;
    pvp: StatsPvp;
    training: StatsTraining;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * StatsTraining
 */
export type StatsTraining = {
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Correct
     */
    correct: number;
    /**
     * Incorrect
     */
    incorrect: number;
    /**
     * Accuracy Pct
     */
    accuracy_pct: number;
    /**
     * Avg Time Ms
     */
    avg_time_ms?: number | null;
    /**
     * By Theme
     */
    by_theme: {
        [key: string]: StatsTrainingByThemeItem;
    };
};

/**
 * StatsTrainingByThemeItem
 */
export type StatsTrainingByThemeItem = {
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Correct
     */
    correct: number;
    /**
     * Incorrect
     */
    incorrect: number;
    /**
     * Accuracy Pct
     */
    accuracy_pct: number;
    /**
     * Avg Time Ms
     */
    avg_time_ms?: number | null;
};

/**
 * TaskSchema
 */
export type TaskSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Subject
     */
    subject: string;
    theme: Theme;
    difficulty: Difficulty;
    /**
     * Title
     */
    title: string;
    /**
     * Task Text
     */
    task_text: string;
    /**
     * Hint
     */
    hint?: string | null;
    /**
     * Answer
     */
    answer?: string | null;
    /**
     * Is Published
     */
    is_published?: boolean;
};

/**
 * TaskSchemaRequest
 */
export type TaskSchemaRequest = {
    /**
     * Subject
     */
    subject: string;
    theme: Theme;
    difficulty: Difficulty;
    /**
     * Title
     */
    title: string;
    /**
     * Task Text
     */
    task_text: string;
    /**
     * Hint
     */
    hint?: string | null;
    /**
     * Answer
     */
    answer?: string | null;
    /**
     * Is Published
     */
    is_published?: boolean;
};

/**
 * Theme
 */
export type Theme = 'математика' | 'русский' | 'информатика' | 'физика';

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * TokenRequest
 */
export type TokenRequest = {
    /**
     * Token
     */
    token: string;
};

/**
 * UserLogIn
 */
export type UserLogIn = {
    /**
     * User Token
     */
    user_token: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Elo Rating
     */
    elo_rating: number;
    /**
     * Is Blocked
     */
    is_blocked: boolean;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Elo Rating
     */
    elo_rating: number;
    /**
     * Is Blocked
     */
    is_blocked: boolean;
};

/**
 * UserSchema
 */
export type UserSchema = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Email
     */
    email: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RegistrationUserApiUserCreatePostData = {
    body: UserSchema;
    path?: never;
    query?: never;
    url: '/api/user/create';
};

export type RegistrationUserApiUserCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegistrationUserApiUserCreatePostError = RegistrationUserApiUserCreatePostErrors[keyof RegistrationUserApiUserCreatePostErrors];

export type RegistrationUserApiUserCreatePostResponses = {
    /**
     * Successful Response
     */
    200: UserLogIn;
};

export type RegistrationUserApiUserCreatePostResponse = RegistrationUserApiUserCreatePostResponses[keyof RegistrationUserApiUserCreatePostResponses];

export type LogInUserApiUserLoginPostData = {
    body: BodyLogInUserApiUserLoginPost;
    path?: never;
    query?: never;
    url: '/api/user/login';
};

export type LogInUserApiUserLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogInUserApiUserLoginPostError = LogInUserApiUserLoginPostErrors[keyof LogInUserApiUserLoginPostErrors];

export type LogInUserApiUserLoginPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LogInUserApiUserLoginPostResponse = LogInUserApiUserLoginPostResponses[keyof LogInUserApiUserLoginPostResponses];

export type GetUserByTokenApiUserTokenGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/token';
};

export type GetUserByTokenApiUserTokenGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserByTokenApiUserTokenGetResponse = GetUserByTokenApiUserTokenGetResponses[keyof GetUserByTokenApiUserTokenGetResponses];

export type GetUserByIdApiUserUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/user/{user_id}';
};

export type GetUserByIdApiUserUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByIdApiUserUserIdGetError = GetUserByIdApiUserUserIdGetErrors[keyof GetUserByIdApiUserUserIdGetErrors];

export type GetUserByIdApiUserUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserByIdApiUserUserIdGetResponse = GetUserByIdApiUserUserIdGetResponses[keyof GetUserByIdApiUserUserIdGetResponses];

export type GetAllUsersApiUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user';
};

export type GetAllUsersApiUserGetResponses = {
    /**
     * Response Get All Users Api User Get
     *
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type GetAllUsersApiUserGetResponse = GetAllUsersApiUserGetResponses[keyof GetAllUsersApiUserGetResponses];

export type PostTasksApiTasksUploadPostData = {
    body: TaskSchemaRequest;
    path?: never;
    query?: never;
    url: '/api/tasks/upload';
};

export type PostTasksApiTasksUploadPostErrors = {
    /**
     * Forbidden - You are not admin
     */
    403: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostTasksApiTasksUploadPostError = PostTasksApiTasksUploadPostErrors[keyof PostTasksApiTasksUploadPostErrors];

export type PostTasksApiTasksUploadPostResponses = {
    /**
     * Successful Response
     */
    200: TaskSchema;
};

export type PostTasksApiTasksUploadPostResponse = PostTasksApiTasksUploadPostResponses[keyof PostTasksApiTasksUploadPostResponses];

export type PostTasksApiTasksUploadImportJsonPostData = {
    body: BodyPostTasksApiTasksUploadImportJsonPost;
    path?: never;
    query?: never;
    url: '/api/tasks/upload/import/json';
};

export type PostTasksApiTasksUploadImportJsonPostErrors = {
    /**
     * Forbidden - You are not admin
     */
    403: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostTasksApiTasksUploadImportJsonPostError = PostTasksApiTasksUploadImportJsonPostErrors[keyof PostTasksApiTasksUploadImportJsonPostErrors];

export type PostTasksApiTasksUploadImportJsonPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ImportTasksApiTasksUploadImportCsvPostData = {
    body: BodyImportTasksApiTasksUploadImportCsvPost;
    path?: never;
    query?: never;
    url: '/api/tasks/upload/import/csv';
};

export type ImportTasksApiTasksUploadImportCsvPostErrors = {
    /**
     * Forbidden - You are not admin
     */
    403: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportTasksApiTasksUploadImportCsvPostError = ImportTasksApiTasksUploadImportCsvPostErrors[keyof ImportTasksApiTasksUploadImportCsvPostErrors];

export type ImportTasksApiTasksUploadImportCsvPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CheckTaskApiTasksTaskIdCheckPostData = {
    body: CheckAnswer;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}/check';
};

export type CheckTaskApiTasksTaskIdCheckPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckTaskApiTasksTaskIdCheckPostError = CheckTaskApiTasksTaskIdCheckPostErrors[keyof CheckTaskApiTasksTaskIdCheckPostErrors];

export type CheckTaskApiTasksTaskIdCheckPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteTaskApiTasksTaskIdDeleteData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type DeleteTaskApiTasksTaskIdDeleteErrors = {
    /**
     * Forbidden - You are not admin
     */
    403: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTaskApiTasksTaskIdDeleteError = DeleteTaskApiTasksTaskIdDeleteErrors[keyof DeleteTaskApiTasksTaskIdDeleteErrors];

export type DeleteTaskApiTasksTaskIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateTaskApiTasksTaskIdPatchData = {
    body: TaskSchema;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type UpdateTaskApiTasksTaskIdPatchErrors = {
    /**
     * Forbidden - You are not admin
     */
    403: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTaskApiTasksTaskIdPatchError = UpdateTaskApiTasksTaskIdPatchErrors[keyof UpdateTaskApiTasksTaskIdPatchErrors];

export type UpdateTaskApiTasksTaskIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTasksApiTasksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/';
};

export type GetTasksApiTasksGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetDefiniteTaskApiTasksGetTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/get/{task_id}';
};

export type GetDefiniteTaskApiTasksGetTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDefiniteTaskApiTasksGetTaskIdGetError = GetDefiniteTaskApiTasksGetTaskIdGetErrors[keyof GetDefiniteTaskApiTasksGetTaskIdGetErrors];

export type GetDefiniteTaskApiTasksGetTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTasksToJsonApiTasksExportGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/export';
};

export type GetTasksToJsonApiTasksExportGetErrors = {
    /**
     * Forbidden - You are not admin
     */
    403: unknown;
};

export type GetTasksToJsonApiTasksExportGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTasksToCsvApiTasksExportCsvGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/export/csv';
};

export type GetTasksToCsvApiTasksExportCsvGetErrors = {
    /**
     * Forbidden - You are not admin
     */
    403: unknown;
};

export type GetTasksToCsvApiTasksExportCsvGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetQueueStatusApiPvpQueueStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pvp/queue-status';
};

export type GetQueueStatusApiPvpQueueStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRecentMatchesApiPvpMatchesRecentGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/pvp/matches/recent';
};

export type GetRecentMatchesApiPvpMatchesRecentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecentMatchesApiPvpMatchesRecentGetError = GetRecentMatchesApiPvpMatchesRecentGetErrors[keyof GetRecentMatchesApiPvpMatchesRecentGetErrors];

export type GetRecentMatchesApiPvpMatchesRecentGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetLeaderboardApiPvpRatingLeaderboardGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/pvp/rating-leaderboard';
};

export type GetLeaderboardApiPvpRatingLeaderboardGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLeaderboardApiPvpRatingLeaderboardGetError = GetLeaderboardApiPvpRatingLeaderboardGetErrors[keyof GetLeaderboardApiPvpRatingLeaderboardGetErrors];

export type GetLeaderboardApiPvpRatingLeaderboardGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ValidateTokenApiAuthValidateTokenPostData = {
    body: TokenRequest;
    path?: never;
    query?: never;
    url: '/api/auth/validate-token';
};

export type ValidateTokenApiAuthValidateTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateTokenApiAuthValidateTokenPostError = ValidateTokenApiAuthValidateTokenPostErrors[keyof ValidateTokenApiAuthValidateTokenPostErrors];

export type ValidateTokenApiAuthValidateTokenPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTasksApiTrainingGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Subject
         */
        subject?: string | null;
        /**
         * Theme
         */
        theme?: Theme | null;
        /**
         * Difficulty
         */
        difficulty?: Difficulty | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Skip
         */
        skip?: number;
    };
    url: '/api/training/';
};

export type GetTasksApiTrainingGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTasksApiTrainingGetError = GetTasksApiTrainingGetErrors[keyof GetTasksApiTrainingGetErrors];

export type GetTasksApiTrainingGetResponses = {
    /**
     * Response Get Tasks Api Training  Get
     *
     * Successful Response
     */
    200: Array<TaskSchema>;
};

export type GetTasksApiTrainingGetResponse = GetTasksApiTrainingGetResponses[keyof GetTasksApiTrainingGetResponses];

export type GetTaskHintApiTrainingTaskTaskIdHintGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/training/task/{task_id}/hint';
};

export type GetTaskHintApiTrainingTaskTaskIdHintGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskHintApiTrainingTaskTaskIdHintGetError = GetTaskHintApiTrainingTaskTaskIdHintGetErrors[keyof GetTaskHintApiTrainingTaskTaskIdHintGetErrors];

export type GetTaskHintApiTrainingTaskTaskIdHintGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CheckAnswerApiTrainingTaskTaskIdCheckPostData = {
    body: CheckAnswer;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/training/task/{task_id}/check';
};

export type CheckAnswerApiTrainingTaskTaskIdCheckPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckAnswerApiTrainingTaskTaskIdCheckPostError = CheckAnswerApiTrainingTaskTaskIdCheckPostErrors[keyof CheckAnswerApiTrainingTaskTaskIdCheckPostErrors];

export type CheckAnswerApiTrainingTaskTaskIdCheckPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMyStatsApiStatsMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/stats/me';
};

export type GetMyStatsApiStatsMeGetResponses = {
    /**
     * Successful Response
     */
    200: StatsResponse;
};

export type GetMyStatsApiStatsMeGetResponse = GetMyStatsApiStatsMeGetResponses[keyof GetMyStatsApiStatsMeGetResponses];

export type GetUserStatsApiStatsUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         *
         * ID пользователя
         */
        user_id: string;
    };
    query?: never;
    url: '/api/stats/users/{user_id}';
};

export type GetUserStatsApiStatsUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserStatsApiStatsUsersUserIdGetError = GetUserStatsApiStatsUsersUserIdGetErrors[keyof GetUserStatsApiStatsUsersUserIdGetErrors];

export type GetUserStatsApiStatsUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: StatsResponse;
};

export type GetUserStatsApiStatsUsersUserIdGetResponse = GetUserStatsApiStatsUsersUserIdGetResponses[keyof GetUserStatsApiStatsUsersUserIdGetResponses];

export type GetMyRatingApiRatingMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rating/me';
};

export type GetMyRatingApiRatingMeGetResponses = {
    /**
     * Successful Response
     */
    200: RatingSummary;
};

export type GetMyRatingApiRatingMeGetResponse = GetMyRatingApiRatingMeGetResponses[keyof GetMyRatingApiRatingMeGetResponses];

export type GetUserRatingApiRatingUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         *
         * ID пользователя
         */
        user_id: string;
    };
    query?: never;
    url: '/api/rating/users/{user_id}';
};

export type GetUserRatingApiRatingUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserRatingApiRatingUsersUserIdGetError = GetUserRatingApiRatingUsersUserIdGetErrors[keyof GetUserRatingApiRatingUsersUserIdGetErrors];

export type GetUserRatingApiRatingUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: RatingSummary;
};

export type GetUserRatingApiRatingUsersUserIdGetResponse = GetUserRatingApiRatingUsersUserIdGetResponses[keyof GetUserRatingApiRatingUsersUserIdGetResponses];

export type GetLeaderboardApiRatingLeaderboardGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/rating/leaderboard';
};

export type GetLeaderboardApiRatingLeaderboardGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLeaderboardApiRatingLeaderboardGetError = GetLeaderboardApiRatingLeaderboardGetErrors[keyof GetLeaderboardApiRatingLeaderboardGetErrors];

export type GetLeaderboardApiRatingLeaderboardGetResponses = {
    /**
     * Successful Response
     */
    200: LeaderboardResponse;
};

export type GetLeaderboardApiRatingLeaderboardGetResponse = GetLeaderboardApiRatingLeaderboardGetResponses[keyof GetLeaderboardApiRatingLeaderboardGetResponses];

export type GetWinProbabilityApiRatingProbabilityGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Opponent Id
         *
         * ID соперника
         */
        opponent_id?: string | null;
        /**
         * Opponent Rating
         *
         * Рейтинг соперника
         */
        opponent_rating?: number | null;
    };
    url: '/api/rating/probability';
};

export type GetWinProbabilityApiRatingProbabilityGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWinProbabilityApiRatingProbabilityGetError = GetWinProbabilityApiRatingProbabilityGetErrors[keyof GetWinProbabilityApiRatingProbabilityGetErrors];

export type GetWinProbabilityApiRatingProbabilityGetResponses = {
    /**
     * Successful Response
     */
    200: ProbabilityResponse;
};

export type GetWinProbabilityApiRatingProbabilityGetResponse = GetWinProbabilityApiRatingProbabilityGetResponses[keyof GetWinProbabilityApiRatingProbabilityGetResponses];

export type GetRatingProjectionApiRatingProjectionGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Opponent Id
         *
         * ID соперника
         */
        opponent_id?: string | null;
        /**
         * Opponent Rating
         *
         * Рейтинг соперника
         */
        opponent_rating?: number | null;
        /**
         * K Factor
         */
        k_factor?: number;
    };
    url: '/api/rating/projection';
};

export type GetRatingProjectionApiRatingProjectionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRatingProjectionApiRatingProjectionGetError = GetRatingProjectionApiRatingProjectionGetErrors[keyof GetRatingProjectionApiRatingProjectionGetErrors];

export type GetRatingProjectionApiRatingProjectionGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectionResponse;
};

export type GetRatingProjectionApiRatingProjectionGetResponse = GetRatingProjectionApiRatingProjectionGetResponses[keyof GetRatingProjectionApiRatingProjectionGetResponses];

export type GetMyRatingHistoryApiRatingHistoryMeGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/rating/history/me';
};

export type GetMyRatingHistoryApiRatingHistoryMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMyRatingHistoryApiRatingHistoryMeGetError = GetMyRatingHistoryApiRatingHistoryMeGetErrors[keyof GetMyRatingHistoryApiRatingHistoryMeGetErrors];

export type GetMyRatingHistoryApiRatingHistoryMeGetResponses = {
    /**
     * Successful Response
     */
    200: MatchHistoryResponse;
};

export type GetMyRatingHistoryApiRatingHistoryMeGetResponse = GetMyRatingHistoryApiRatingHistoryMeGetResponses[keyof GetMyRatingHistoryApiRatingHistoryMeGetResponses];
